In [1]:
import cv2
import numpy as np

#### 读入图像

In [2]:
img = cv2.imread('test.png')  

In [3]:
cv2.imshow('name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

#### 读入图像转换为灰度图像

In [5]:
#img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#### 彩色转灰度的公式
$Gray = R*0.299 + G*0.587 + B*0.114$

In [4]:
bImg, gImg, rImg = cv2.split(img)  # 拆分为 BGR 独立通道
Grayimg = np.zeros_like(bImg,dtype = 'uint8')  # 创建与 bImg 相同形状的黑色图像 
Grayimg = rImg*0.299 + gImg*0.587 + bImg*0.114

print(Grayimg)
#Grayimg = (np.uint8)(rImg*0.299 + gImg*0.587 + bImg*0.114)

cv2.imshow('Grayimg',Grayimg)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

[[156.424 156.31  155.783 ...  64.65   54.953  49.387]
 [156.609 156.196 156.082 ...  55.426  51.501  48.761]
 [156.022 155.609 155.196 ...  45.871  44.604  46.337]
 ...
 [ 81.387  82.028  81.381 ... 105.074 112.732 118.689]
 [127.414 128.468 128.935 ... 144.742 148.699 151.77 ]
 [255.    255.    255.    ... 255.    255.    255.   ]]


2022-09-01 11:50:42.370 python[3879:82467] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (80.10 secs).


-1