In [1]:
import cv2
import numpy as np

#### 读入图像

In [2]:
img = cv2.imread('test.png')  
#img = cv2.imread('image\h.png',cv2.IMREAD_GRAYSCALE)

In [3]:
cv2.imshow('name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [5]:
type(img)

numpy.ndarray

In [6]:
img.shape

(340, 340, 3)

In [7]:
print(img)

[[[110 130 226]
  [109 130 226]
  [107 130 225]
  ...
  [ 67  36 120]
  [ 65  27 106]
  [ 63  23  96]]

 [[109 130 227]
  [108 130 226]
  [107 130 226]
  ...
  [ 64  28 106]
  [ 66  25  98]
  [ 68  23  92]]

 [[109 129 227]
  [108 129 226]
  [107 129 225]
  ...
  [ 58  19  94]
  [ 60  19  89]
  [ 65  22  87]]

 ...

 [[ 88  64 113]
  [ 91  64 114]
  [ 93  62 115]
  ...
  [101  84 148]
  [106  92 156]
  [109  98 163]]

 [[132 114 152]
  [136 114 154]
  [140 113 156]
  ...
  [141 127 181]
  [142 131 186]
  [143 134 190]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [8]:
img[0][0]

array([110, 130, 226], dtype=uint8)

In [9]:
img[0][1]

array([109, 130, 226], dtype=uint8)

In [10]:
img[1][0]

array([109, 130, 227], dtype=uint8)

#### 读入图像转换为灰度图像

In [11]:
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [12]:
print(img,img.shape)

[[156 156 156 ...  65  55  49]
 [157 156 156 ...  55  52  49]
 [156 156 155 ...  46  45  46]
 ...
 [ 81  82  81 ... 105 113 119]
 [127 128 129 ... 145 149 152]
 [255 255 255 ... 255 255 255]] (340, 340)


In [13]:
cv2.imshow('name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

2022-09-01 11:47:47.058 python[3777:79821] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (90.82 secs).


-1

#### 转换为黑白图像

In [14]:
ret,img = cv2.threshold(img,128,255,cv2.THRESH_BINARY)

In [15]:
cv2.imshow('name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

#### 写图像

In [ ]:
cv2.imwrite('image\h_gray.png',img)

## 如何用代码实现cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)的功能？